<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scss</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*|^#|^\*|^\b|^\.</string>
	<key>foldingStopMarker</key>
	<string>\*/|^\s*$</string>
	<key>name</key>
	<string>SCSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?&lt;=^|\]|}|\)|not\(|\*):(?=[\w-])</string>
			<key>end</key>
			<string>$|(?=\s|,|;|\.|\(|\)|\[|{|>|\+|~)</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-class.css.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$[\w-]+)(?=:\s*\()|(?&lt;=(\s|,)\($)</string>
			<key>end</key>
			<string>;|\)\s*$</string>
			<key>name</key>
			<string>map-outer.sass</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>$|(?=,\s*\w+:|;)</string>
					<key>name</key>
					<string>property-value.sass</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline-comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quoted</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#flag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parent-selector</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function-quoted</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rgb</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numeric</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#unit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reserved-words</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#property-value</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>end</key>
			<string>;|(?=\s\(|and\(|{|})</string>
			<key>name</key>
			<string>property-value.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parent-selector</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rgb</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserved-words</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline-comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolation</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>@include</string>
			<key>end</key>
			<string>$|(?=\(|{|;)</string>
			<key>name</key>
			<string>support.function.name.sass.library</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>@mixin|@function</string>
			<key>end</key>
			<string>$|(?=\(|{)</string>
			<key>name</key>
			<string>support.function.name.sass.no-completions</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css.sass</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\w-]+</string>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>@</string>
			<key>end</key>
			<string>$|\s(?!(all|braille|embossed|handheld|print|projection|speech|tty|tv|if)(\s|,))|(?=;)</string>
			<key>name</key>
			<string>keyword.control.at-rule.css.sass</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-quoted</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\d)%(?!\d)</string>
			<key>end</key>
			<string>$|(?=\s|;|{)</string>
			<key>name</key>
			<string>entity.other.attribute-name.placeholder-selector.sass</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\-|\()\b(a|abbr|acronym|address|applet|area|article|aside|audio|b|base|big|blockquote|body|br|button|canvas|caption|cite|code|col|colgroup|datalist|dd|del|details|dfn|dialog|div|dl|dt|em|embed|eventsource|fieldset|figure|figcaption|footer|form|frame|frameset|(h[1-6])|head|header|hgroup|hr|html|i|iframe|img|input|ins|kbd|label|legend|li|link|map|mark|menu|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|picture|pre|progress|q|samp|script|section|select|small|source|span|strike|strong|style|sub|summary|sup|table|tbody|td|textarea|template|tfoot|th|thead|time|title|tr|tt|ul|var|video|main|svg|rect|ruby|center|circle|ellipse|line|polyline|polygon|path|text|u|x)\b(?!-|\))</string>
			<key>end</key>
			<string>$|(?=\s|,|;|#|\.|\(|\)|\[|{|>|\+|~)</string>
			<key>name</key>
			<string>entity.name.tag.css.sass.symbol</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#pseudo-class</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>entity.other.attribute-selector.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quoted</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\^|\$|\*|~</string>
					<key>name</key>
					<string>keyword.other.regex.sass</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$|(?=\s|,|;|\.|\(|\)|\[|{|>|\+|~)</string>
			<key>name</key>
			<string>entity.other.attribute-name.id.css.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pseudo-class</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\.)|(&amp;)</string>
			<key>end</key>
			<string>$|(?=\s|,|;|#|\(|\)|\[|{|>|\+|~)</string>
			<key>name</key>
			<string>entity.other.attribute-name.class.css.sass</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.important.css.sass</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pseudo-class</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#flag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rgb</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unit</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserved-words</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\w-]*\w+\b(?!\s*:|-)</string>
			<key>name</key>
			<string>meta.property-value.css.sass, support.constant.property-value.css.sass</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\$[\w-]*|\.{3}</string>
			<key>name</key>
			<string>variable.other.sass</string>
		</dict>
		<key>function</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s|\(|,|:|{)(?!url|format|attr)[\w\.-]+(?=\()</string>
			<key>name</key>
			<string>support.function.name.sass</string>
		</dict>
		<key>function-quoted</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=url\(|format\(|attr\().+?(?=\))</string>
			<key>name</key>
			<string>string.quoted.sass</string>
		</dict>
		<key>parent-selector</key>
		<dict>
			<key>match</key>
			<string>&amp;</string>
			<key>name</key>
			<string>keyword.other.important.css.sass</string>
		</dict>
		<key>pseudo-class</key>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>end</key>
			<string>$|(?=\s|,|;|\.|\(|\)|\[|{|>|\+|~)</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-class.css.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>property-value</key>
		<dict>
			<key>match</key>
			<string>[\w-]+</string>
			<key>name</key>
			<string>meta.property-value.css.sass, support.constant.property-value.css.sass</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b\d+\.?\d*</string>
			<key>name</key>
			<string>constant.numeric.css.sass</string>
		</dict>
		<key>unit</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\d|})(em|ex|ch|rem|vh|vw|vmin|vmax|px|mm|cm|in|pt|pc|deg|grad|rad|turn|Hz|kHz|dpi|dpcm|dppx|s|ms|%)</string>
			<key>name</key>
			<string>keyword.other.unit.css.sass</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>\+|\s-\s|\s-(?=\$)|(?&lt;=\()-(?=\$)|\s-(?=\()|\*|/|%|=|!|&lt;|&gt;|~</string>
			<key>name</key>
			<string>keyword.operator.sass</string>
		</dict>
		<key>rgb</key>
		<dict>
			<key>match</key>
			<string>(#)([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b</string>
			<key>name</key>
			<string>constant.other.color.rgb-value.css.sass</string>
		</dict>
		<key>flag</key>
		<dict>
			<key>match</key>
			<string>!(important|default|optional|global)</string>
			<key>name</key>
			<string>keyword.other.important.css.sass</string>
		</dict>
		<key>reserved-words</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|from|through|to|in|or|and|not|screen)\b(?!-)</string>
			<key>name</key>
			<string>keyword.other.important.css.sass</string>
		</dict>
		<key>comment-tag</key>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>comment.tag-outer.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\w-]+</string>
					<key>name</key>
					<string>comment.tag.sass</string>
				</dict>
			</array>
		</dict>
		<key>inline-comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>quoted</key>
		<dict>
			<key>begin</key>
			<string>('|")(?=.*\1)</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.quoted.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quoted-interpolation</string>
				</dict>
			</array>
		</dict>
		<key>quoted-interpolation</key>
		<dict>
			<key>begin</key>
			<string>#{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>interpolation-outer.sass</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.interpolation.sass</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>begin</key>
			<string>#{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>interpolation-outer.sass</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.interpolation.sass</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scss</string>
	<key>uuid</key>
	<string>90DAEA60-88AA-11E2-9E96-0800200C9A66</string>
</dict>
</plist>
